version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitSyncAndScaffoldingTesProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQAGitSyncAndScaffoldingTesProject
  gitUsername: siqagituser
  gitBranch: main
